//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evento
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventosEntities : DbContext
    {
        public EventosEntities()
            : base("name=EventosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Participante> Participantes { get; set; }
        public DbSet<Estado> Estadoes { get; set; }
        public DbSet<Evento> Eventoes { get; set; }
        public DbSet<GrauAcademico> GrauAcademicoes { get; set; }
        public DbSet<Publicacao> Publicacaos { get; set; }
        public DbSet<Sexo> Sexoes { get; set; }
        public DbSet<TipoEvento> TipoEventoes { get; set; }
        public DbSet<TipoParticipante> TipoParticipantes { get; set; }
    }
}
