//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Participantes = new HashSet<Participante>();
            this.Publicacaos = new HashSet<Publicacao>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<int> idTipoEvento { get; set; }
        public string descricao { get; set; }
        public string local { get; set; }
        public string agenda { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual ICollection<Participante> Participantes { get; set; }
        public virtual ICollection<Publicacao> Publicacaos { get; set; }
    }
}
