//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public int id { get; set; }
        public Nullable<int> idTipoParticipante { get; set; }
        public string nome { get; set; }
        public string apelido { get; set; }
        public Nullable<int> idGrau { get; set; }
        public string empresa { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public Nullable<int> sexo { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public Nullable<int> idEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual GrauAcademico GrauAcademico { get; set; }
        public virtual Sexo Sexo1 { get; set; }
        public virtual TipoParticipante TipoParticipante { get; set; }
    }
}
