//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacao
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dataPublicacao { get; set; }
        public Nullable<int> idEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
